repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile
          - black
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types:
          - python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args:
          - --strict
          - --no-warn-no-return
        exclude: ^(tests|platform_utils/pytest_plugins)
        additional_dependencies: [
          "pydantic", "gql", "pydantic_settings"
        ]
  - repo: local
    hooks:
      - id: poetry-lock-check
        name: "check poetry lock file"
        entry: bash -c "poetry lock --check"
        language: system