"""Constants to be used in tests."""

CREATE_TAKE_MUTATION = "createSingleCamTake"
UPDATE_TAKE_MUTATION = "updateTake"
GET_TAKE_QUERY = "getTake"
LIST_TAKES_QUERY = "listTakes"
CREATE_JOB_MUTATION = "createSingleCamJob"
GET_JOB_QUERY = "getJob"
LIST_JOBS_QUERY = "listJobs"
UPDATE_JOB_MUTATION = "updateJob"
UPDATE_CLIENT_MUTATION = "updateClient"
GET_CLIENT_QUERY = "client"
CREATE_FILE_MUTATION = "createFile"
UPDATE_FILE_MUTATION = "updateFile"
CLIENT_LITERAL = "client"
