"""Constants to be used in tests."""

CREATE_TAKE_MUTATION = "createTake"
UPDATE_TAKE_MUTATION = "updateTake"
GET_TAKE_QUERY = "getTake"
CREATE_JOB_MUTATION = "createJob"
GET_JOB_QUERY = "getJob"
UPDATE_CLIENT_MUTATION = "updateClient"
GET_CLIENT_QUERY = "client"
CREATE_FILE_MUTATION = "createFile"
UPDATE_FILE_MUTATION = "updateFile"
CLIENT_LITERAL = "client"
