name: 'Set up python base for this repository'
description: 'Sets up python and install all dependencies'
inputs:
  version:
    description: 'Python version to be set up'
    required: true
  groups:
    description: 'Poetry groups to install'
    required: false
    default: "dev"


runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}
        cache: "poetry"
    - name: Install python dependencies
      shell: bash
      run: |
        poetry install --no-interaction --no-root --with ${{ inputs.groups }}