name: Release

# Run on every version tag (0.1.0, 0.1.1 and so on)
on:
  push:
    tags:
      - "*"


jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Integration tests
    strategy:
      fail-fast: false
      matrix:
        test-name:
          - "create_volume_with_human"
          - "create_multi_cam_take"
          - "create_multi_cam_job"
          - "create_single_cam_take"
          - "create_single_cam_job"
          - "list_takes"
          - "list_jobs"
          - "list_volumes"
          - "list_rigs"
          - "create_files"
          - "share_files"
          - "update_file"
          - "update_job"
          - "update_take"
      
    steps:
      - uses: actions/checkout@v4
        with:
          repository: move-ai/move-services-testing
          ssh-key: ${{ secrets.INTEGRATION_TESTS_PRIVATE_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run test suite
        # Must be relative path because we're using an action from local path
        uses: ./.github/actions/ugc-python
        with:
          test-name: ${{ matrix.test-name }}
          api-key: ${{ secrets.API_KEY_QA_CLIENT_DEFAULT }}
          endpoint-url: ${{ secrets.UGC_API_ENDPOINT_URL }}
          python-version: "3.11"
          rev: ${{ github.sha }}

  publish:
    name: "Publish ${{ github.ref_name }}"
    runs-on: "ubuntu-latest"
    environment: Production
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    needs:
      - integration-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up python and dependencies
        uses: ./.github/actions/base-python
        with:
          version: "3.10"
      - name: Build dist/**
        run: |
          poetry build
      - name: Publish to PyPI
        # By default, this action will publish to PyPI from `.dist/*` path.
        # We don't need to specific any API tokens here since trusted publishing is set up
        # See https://docs.pypi.org/trusted-publishers/using-a-publisher/
        uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: "Release ${{ github.ref_name }}"
    runs-on: "ubuntu-latest"
    needs:
      - integration-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up python and dependencies
        uses: ./.github/actions/base-python
        with:
          version: "3.10"
          groups: "docs"
      - name: Configure git user for mike
        run: |
          git fetch origin gh-pages --depth=1
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Target latest docs to ${{ github.ref_name }}
        run: |
          poetry run mike deploy --push --update-aliases ${{ github.ref_name }} latest